spring:
#  cloud:
#    openfeign:
#      client:
#        config:
#          secureServiceClient:
#            requestInterceptors:
#              - org.springframework.cloud.openfeign.security.OAuth2AccessTokenInterceptor
#          UnsecureServiceClient:
#            requestInterceptors: []
  security:
    oauth2:
      client:
        registration:
          demo-client:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            clientAuthenticationMethod: "client_secret_post"
            authorizationGrantType: "client_credentials"
            provider: "demo-client"
        provider:
          demo-client:
            token-uri: "http://127.0.0.1:4444/oauth2/token"
server:
  port: 8081

feign:

logging:
  level:
    com.example.secureclient.clients: DEBUG
