spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

external-services:
  mindbox:
    endpointId: "finlive.mailings"
    secretKey: ${MINDBOX_SECRET_KEY}
