---
version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: emails
