spring:
  application:
    name: scg-demo1
  cloud:
    gateway:
      routes:
        - id: book-route
          uri: ${BOOKS_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books/?(?<segment>.*), /${segment}
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy
            - name: Retry
              args:
                retires: 3
                methods: GET
                backoffs:
                  firstBackoff: 50ms
                  maxBackoff: 1000ms
