
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://127.0.0.1:4445/admin/oauth2/introspect
          client-id: client
          client-secret: secret
server:
  port: 8080
